### ISSUE TITLE
Criação da página "sobre"

### ISSUE THREAD

**Issue by ade10x100** [ARMDevBR/GitHubCourse#3]
Vocês poderiam criar uma página de "sobre"? Agradeço.

**Comment by ARMDevBR** [comment]
A página já está em produção.

**Comment by ade10x100** [comment]
Obrigado. Estou aguardando.

________________________________
De: ARMDevBR <notifications@github.com>
Enviado: terça-feira, 9 de janeiro de 2018 19:39:42
Para: ARMDevBR/GitHubCourse
Cc: ade10x100; Author
Assunto: Re: [ARMDevBR/GitHubCourse] Criação da página "sobre" (#3)


A página já está em produção.
